### ISSUE TITLE
Invalid keys in stanza

### ISSUE THREAD

**Issue by edro15** [seunomosowon/TA-mailclient#19]
**OS details**
```bash
  Operating System: CentOS Linux 7 (Core)
  Kernel: Linux 3.10.0-1127.13.1.el7.x86_64
  Architecture: x86-64
```
**Steps performed**
* installed the app in a single server Splunk 7.3 instance, 
* configured `local/inputs.conf` following documentation, and 
* restarted splunk.

At restart, during Splunk conf files check, I got the following errors:
```bash
    Checking conf files for problems...
		Invalid key in stanza [mail://email_address@domain.com] in $SPLUNK_HOME/etc/apps/TA-mailclient/local/inputs.conf, line 3: is_secure  (value:  1).
		Invalid key in stanza [mail] in $SPLUNK_HOME/etc/apps/TA-mailclient/default/inputs.conf, line 2: python.version  (value:  python3).
		Your indexes and inputs configurations are not internally consistent. For more information, run 'splunk btool check --debug'
```

**Comment by seunomosowon** [comment]
You can take is_secure out. I reconfigured the new version of the app to
only support secure connection to mailboxes, so that parameter has been
removed.

I should have put a note on the réarme to say that needs to be removed
going forward.

Cheers,
Seun
