### ISSUE TITLE
Error thrown, continues to connect to mailbox but indexing stops

### ISSUE THREAD

**Issue by spoonachario** [seunomosowon/TA-mailclient#5]
- Splunk Version 7.0.0 on Ubuntu
- TA version 1.3.7dev
- MS Exchange mailbox

Hi Seun,

I'm running into a few emails with attachments that seem to stop TA-mailclient from continuing to index emails (via IMAP), the background process continues to execute (as seen in the logs below) but no further emails will be indexed. Log extract attached.
[logs.txt](https://github.com/seunomosowon/TA-mailclient/files/1706063/logs.txt)

If I delete that specific email from the mailbox directly and restart the Splunk/TA-mailclient it will continue to index again until it hits the next email with an issue. There are thousands of other emails from this mailbox that are being indexed fine.

Thanks

**Comment by seunomosowon** [comment]
Hi, 
Does this work fine with v1.3.5? There are some encodings that are not supported by the python that comes bundled with Splunk. I'm looking for a way to package it with more character sets during my spare time. I started tinkering around with it in v1.3.6dev / v1.3.7dev. 

You closed the issue - Does that mean it indexed it?

**Comment by jtran9373** [comment]
hi 
where can I download v1.3.7?  could you please provide the links?
thank you
