### ISSUE TITLE
Request: Support indexing mails from additional folders in a mailbox

### ISSUE THREAD

**Issue by Paul1896** [seunomosowon/TA-mailclient#8]
Hey Seun!

thank you very much for the great TA! We're really looking forward for a future support of indexing mails from additional folders in a mailbox.

May you have already some information or timeline for implement this feature.

Thank you very much!

**Comment by lowell80** [comment]
I need this feature as well.   I plan to implement this for a project I'm working on unless anyone else speaks up having already implemented it.

I'm assuming this is an IMAP only feature, since I don't think POP3 supports this concept (but then again, I haven't even thought about POP3 in the last decade.  lol)

**Comment by seunomosowon** [comment]
Thanks Lowell. Looks good. I had a quick look. I’m going to try update the Travis config this weekend so it tests with Splunk v8.
I actually thought most people would switch to using Phantom to fetch emails, but I guess this app might still be needed for ingesting mails directly to Splunk.

**Comment by lowell80** [comment]
Yeah, I would expect Phantom to be a better approach, when available.  (I believe the use case ultimately being supported is a security one, now that you mention it), but Phantom isn't in the mix at the moment, but I suspect that Splunk Enterprise/Cloud will always be more broadly deployed.

Thanks for your consideration.

**Comment by seunomosowon** [comment]
I've just added support for this. I should merge this into the master branch later tonight.

You will get something like this in the logs now which shows the additional folders seen in the inbox:
ExecProcessor - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-mailclient/bin/mail.py" Retrieved 2 mails from mailbox: pop_to_splunk@aol.com/subfolder
ExecProcessor - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-mailclient/bin/mail.py" Retrieved 8 mails from mailbox: pop_to_splunk@aol.com/inbox
ExecProcessor - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-mailclient/bin/mail.py" Accessing mailbox with readonly attribute
ExecProcessor - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-mailclient/bin/mail.py" Folders found: Archive,Bulk Mail,Draft,Inbox,Saved,Saved/SavedIMs,Sent,Trash,subfolder
ExecProcessor - message from "/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/TA-mailclient/bin/mail.py" Listing folders in mailbox=pop_to_splunk@aol.com
